<a href="https://colab.research.google.com/github/afriveros/LaboratorioECCIBigData/blob/main/siniestros_viales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PROYECTO SINIESTROS VIALES
## Elaborado Por Docente Elias Buitrago Bolivar
# Laboratorio realizado por Andrés Felipe Riveros 83331 Universidad ECCI
### Fecha 16/07/2024

En este cuaderno de jupyter se realiza un flujo de trabajo para predecir la severidad de siniestros viales, a partir de una base de datos de la Secretaría Distrital.

### Importar librerías

In [40]:
import numpy as np
import pandas as pd

### Cargar datos

In [41]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Se agregó la linea "encoding='latin-1'" debido a que no realizaba lectura del archivo

In [42]:
# dataini = pd.read_csv('historico_siniestros_bogota_d.c_-.csv')
dataini = pd.read_csv('/content/drive/MyDrive/SEMINARIO BIG DATA/historico_siniestros_bogota_d.c.csv', encoding='latin-1')

In [43]:
dataini.head()

ÿX         Y  OBJECTID  FORMULARIO  CODIGO_ACCIDENTE  \
0 -74.090924  4.693807         1  A000640275           4484660   
1 -74.121000  4.603000         2  A001233353          10533499   
2 -74.042000  4.682000         4  A001232786          10533629   
3 -74.166937  4.587187         7  A000200705           4412699   
4 -74.092901  4.607648         8  A000402862           4447845   

     FECHA_OCURRENCIA_ACC  ANO_OCURRENCIA_ACC                   DIRECCION  \
0  2017/06/12 00:00:00+00                2017  AV AVENIDA BOYACA-CL 79 02   
1  2020/11/19 00:00:00+00                2020           CL 26 S- KR 50 02   
2  2020/11/10 00:00:00+00                2020            KR 9 - CL 100 02   
3  2015/05/11 00:00:00+00                2015           CL 63A-KR 72 S 02   
4  2016/06/08 00:00:00+00                2016               KR 27-CL 9 14   

      GRAVEDAD CLASE_ACC       LOCALIDAD          FECHA_HORA_ACC   LATITUD  \
0   SOLO DANOS    CHOQUE        ENGATIVA  2017/06/12 05:30:00+00  4.693807   
1  CON HERIDOS      OTRO   PUENTE ARANDA  2020/11/19 02:05:00+00  4.603000   
2   SOLO DANOS    CHOQUE         USAQUEN  2020/11/10 13:30:00+00  4.682000   
3   SOLO DANOS    CHOQUE  CIUDAD BOLIVAR  2015/05/11 10:50:00+00  4.587187   
4   SOLO DANOS    CHOQUE    LOS MARTIRES  2016/06/08 21:30:00+00  4.607648   

    LONGITUD         CIV  PK_CALZADA  
0 -74.090924  10006772.0    221236.0  
1 -74.121000  16004560.0         NaN  
2 -74.042000  30001107.0         NaN  
3 -74.166937  19001483.0    136166.0  
4 -74.092901  14000548.0    239719.0

A la columna llamada X se le agregó ÿ

In [44]:
data = dataini

data = data.drop(['ÿX','Y','OBJECTID','FORMULARIO','CODIGO_ACCIDENTE','FECHA_OCURRENCIA_ACC','ANO_OCURRENCIA_ACC','DIRECCION','CIV','PK_CALZADA', ], axis=1)
data.head()

GRAVEDAD CLASE_ACC       LOCALIDAD          FECHA_HORA_ACC   LATITUD  \
0   SOLO DANOS    CHOQUE        ENGATIVA  2017/06/12 05:30:00+00  4.693807   
1  CON HERIDOS      OTRO   PUENTE ARANDA  2020/11/19 02:05:00+00  4.603000   
2   SOLO DANOS    CHOQUE         USAQUEN  2020/11/10 13:30:00+00  4.682000   
3   SOLO DANOS    CHOQUE  CIUDAD BOLIVAR  2015/05/11 10:50:00+00  4.587187   
4   SOLO DANOS    CHOQUE    LOS MARTIRES  2016/06/08 21:30:00+00  4.607648   

    LONGITUD  
0 -74.090924  
1 -74.121000  
2 -74.042000  
3 -74.166937  
4 -74.092901

In [45]:
# df['year'], df['month'] = df['date'].dt.year, df['date'].dt.month
# data['AÑO'] = data['FECHA_OCURRENCIA_ACC'].
data['AÑO'] = pd.DatetimeIndex(data['FECHA_HORA_ACC']).year

In [46]:
data['MES'] = pd.DatetimeIndex(data['FECHA_HORA_ACC']).month

In [47]:
data['DIA'] = pd.DatetimeIndex(data['FECHA_HORA_ACC']).day

In [48]:
# data['HORA'] = pd.DatetimeIndex(data['FECHA_HORA_ACC']).time #HH:MM:SS
data['HORA'] = pd.DatetimeIndex(data['FECHA_HORA_ACC']).hour #HH

In [49]:
data.head()

GRAVEDAD CLASE_ACC       LOCALIDAD          FECHA_HORA_ACC   LATITUD  \
0   SOLO DANOS    CHOQUE        ENGATIVA  2017/06/12 05:30:00+00  4.693807   
1  CON HERIDOS      OTRO   PUENTE ARANDA  2020/11/19 02:05:00+00  4.603000   
2   SOLO DANOS    CHOQUE         USAQUEN  2020/11/10 13:30:00+00  4.682000   
3   SOLO DANOS    CHOQUE  CIUDAD BOLIVAR  2015/05/11 10:50:00+00  4.587187   
4   SOLO DANOS    CHOQUE    LOS MARTIRES  2016/06/08 21:30:00+00  4.607648   

    LONGITUD   AÑO  MES  DIA  HORA  
0 -74.090924  2017    6   12     5  
1 -74.121000  2020   11   19     2  
2 -74.042000  2020   11   10    13  
3 -74.166937  2015    5   11    10  
4 -74.092901  2016    6    8    21

In [50]:
data = data.drop('FECHA_HORA_ACC',axis=1)
data.head()

GRAVEDAD CLASE_ACC       LOCALIDAD   LATITUD   LONGITUD   AÑO  MES  DIA  \
0   SOLO DANOS    CHOQUE        ENGATIVA  4.693807 -74.090924  2017    6   12   
1  CON HERIDOS      OTRO   PUENTE ARANDA  4.603000 -74.121000  2020   11   19   
2   SOLO DANOS    CHOQUE         USAQUEN  4.682000 -74.042000  2020   11   10   
3   SOLO DANOS    CHOQUE  CIUDAD BOLIVAR  4.587187 -74.166937  2015    5   11   
4   SOLO DANOS    CHOQUE    LOS MARTIRES  4.607648 -74.092901  2016    6    8   

   HORA  
0     5  
1     2  
2    13  
3    10  
4    21

In [51]:
data.shape

(199146, 9)

In [52]:
data = pd.get_dummies(data, columns=['CLASE_ACC','LOCALIDAD'])
data.head()

GRAVEDAD   LATITUD   LONGITUD   AÑO  MES  DIA  HORA  \
0   SOLO DANOS  4.693807 -74.090924  2017    6   12     5   
1  CON HERIDOS  4.603000 -74.121000  2020   11   19     2   
2   SOLO DANOS  4.682000 -74.042000  2020   11   10    13   
3   SOLO DANOS  4.587187 -74.166937  2015    5   11    10   
4   SOLO DANOS  4.607648 -74.092901  2016    6    8    21   

   CLASE_ACC_ATROPELLO  CLASE_ACC_AUTOLESION  CLASE_ACC_CAIDA DE OCUPANTE  \
0                False                 False                        False   
1                False                 False                        False   
2                False                 False                        False   
3                False                 False                        False   
4                False                 False                        False   

   ...  LOCALIDAD_PUENTE ARANDA  LOCALIDAD_RAFAEL URIBE URIBE  \
0  ...                    False                         False   
1  ...                     True                         False   
2  ...                    False                         False   
3  ...                    False                         False   
4  ...                    False                         False   

   LOCALIDAD_SAN CRISTOBAL  LOCALIDAD_SANTA FE  LOCALIDAD_SUBA  \
0                    False               False           False   
1                    False               False           False   
2                    False               False           False   
3                    False               False           False   
4                    False               False           False   

   LOCALIDAD_SUMAPAZ  LOCALIDAD_TEUSAQUILLO  LOCALIDAD_TUNJUELITO  \
0              False                  False                 False   
1              False                  False                 False   
2              False                  False                 False   
3              False                  False                 False   
4              False                  False                 False   

   LOCALIDAD_USAQUEN  LOCALIDAD_USME  
0              False           False  
1              False           False  
2               True           False  
3              False           False  
4              False           False  

[5 rows x 34 columns]

In [53]:
data.shape

(199146, 34)

In [54]:
data.dtypes

GRAVEDAD                         object
LATITUD                         float64
LONGITUD                        float64
AÑO                               int32
MES                               int32
DIA                               int32
HORA                              int32
CLASE_ACC_ATROPELLO                bool
CLASE_ACC_AUTOLESION               bool
CLASE_ACC_CAIDA DE OCUPANTE        bool
CLASE_ACC_CHOQUE                   bool
CLASE_ACC_INCENDIO                 bool
CLASE_ACC_OTRO                     bool
CLASE_ACC_VOLCAMIENTO              bool
LOCALIDAD_ANTONIO NARINO           bool
LOCALIDAD_BARRIOS UNIDOS           bool
LOCALIDAD_BOSA                     bool
LOCALIDAD_CANDELARIA               bool
LOCALIDAD_CHAPINERO                bool
LOCALIDAD_CIUDAD BOLIVAR           bool
LOCALIDAD_ENGATIVA                 bool
LOCALIDAD_FONTIBON                 bool
LOCALIDAD_KENNEDY                  bool
LOCALIDAD_LOS MARTIRES             bool
LOCALIDAD_PUENTE ARANDA            bool


In [55]:
data['GRAVEDAD']

0          SOLO DANOS
1         CON HERIDOS
2          SOLO DANOS
3          SOLO DANOS
4          SOLO DANOS
             ...     
199141     SOLO DANOS
199142    CON HERIDOS
199143    CON HERIDOS
199144    CON HERIDOS
199145    CON HERIDOS
Name: GRAVEDAD, Length: 199146, dtype: object

In [56]:
data['GRAVEDAD'] = pd.Categorical(data['GRAVEDAD'])
categories = data.GRAVEDAD.cat.categories
codes = data.GRAVEDAD.cat.codes

In [57]:
categories

Index(['CON HERIDOS', 'CON MUERTOS', 'SOLO DANOS'], dtype='object')

In [58]:
data['GRAVEDAD'] = data.GRAVEDAD.cat.codes
data.dtypes

GRAVEDAD                           int8
LATITUD                         float64
LONGITUD                        float64
AÑO                               int32
MES                               int32
DIA                               int32
HORA                              int32
CLASE_ACC_ATROPELLO                bool
CLASE_ACC_AUTOLESION               bool
CLASE_ACC_CAIDA DE OCUPANTE        bool
CLASE_ACC_CHOQUE                   bool
CLASE_ACC_INCENDIO                 bool
CLASE_ACC_OTRO                     bool
CLASE_ACC_VOLCAMIENTO              bool
LOCALIDAD_ANTONIO NARINO           bool
LOCALIDAD_BARRIOS UNIDOS           bool
LOCALIDAD_BOSA                     bool
LOCALIDAD_CANDELARIA               bool
LOCALIDAD_CHAPINERO                bool
LOCALIDAD_CIUDAD BOLIVAR           bool
LOCALIDAD_ENGATIVA                 bool
LOCALIDAD_FONTIBON                 bool
LOCALIDAD_KENNEDY                  bool
LOCALIDAD_LOS MARTIRES             bool
LOCALIDAD_PUENTE ARANDA            bool


In [59]:
data['GRAVEDAD'].head()

0    2
1    0
2    2
3    2
4    2
Name: GRAVEDAD, dtype: int8

In [60]:
X = data.drop('GRAVEDAD', axis=1)
X.shape

(199146, 33)

In [61]:
Y=pd.DataFrame()
Y['GRAVEDAD'] = data['GRAVEDAD']
Y.shape

(199146, 1)

In [62]:
print(data['GRAVEDAD'].value_counts(normalize=True).mul(100).round(1).astype(str)+'%')

GRAVEDAD
2    64.4%
0    34.0%
1     1.6%
Name: proportion, dtype: object


### Transformación datos: media cero y varianza unitaria

In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
# Media cero y varianza unitaria
sc = StandardScaler()
Xsc = sc.fit(X)
Xt = Xsc.transform(X)
Xt.shape


(199146, 33)

### Partición conjuntos de datos: Entrenamiento, prueba y validación, se quitó el comentario en el segundo conjunto de comandos para ejecutar redes neuronales

In [65]:
from sklearn.model_selection import train_test_split as split

In [74]:
## # Definir función para particionar el conjunto de datos

X_train, X_test, y_train, y_test = split(Xt,Y,
                                         test_size=0.30,
                                         random_state=42,
                                         stratify=Y)

X_train, X_valid, y_train, y_valid = split(X_train, y_train,
                                            test_size=0.2,
                                            stratify=y_train)

## Modelos Supervisados

### Árboles de decisión, se quitó el comentario en la primera linea

In [88]:
import xgboost as xgb
from sklearn import metrics
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [104]:
#Definición del modelo
arbol1 = DecisionTreeClassifier()

#Entrenamiento y evaluación del modelo
arbol1 = arbol1.fit(X_train,y_train)

# Calcular métricas de desempeño
y_pred = arbol1.predict(X_test)
print("\n", metrics.classification_report(y_test, y_pred, digits=2))

# Visualizar matriz de confusión
Y_pred = np_utils.to_categorical(y_pred)
cm = matriz_confusion(Y_test, y_pred, 'si', 'Matriz de confusión clasificador AD')


               precision    recall  f1-score   support

           0       0.53      0.54      0.53     20310
           1       0.07      0.08      0.07       972
           2       0.76      0.75      0.76     38462

    accuracy                           0.67     59744
   macro avg       0.45      0.46      0.45     59744
weighted avg       0.67      0.67      0.67     59744



NameError: name 'matriz_confusion' is not defined

### Random Forests

In [90]:
from sklearn.ensemble import RandomForestClassifier

In [91]:
#Definición del modelo
rfc = RandomForestClassifier(n_estimators=200)

#Entrenamiento y evaluación del modelo
rfc.fit(X_train, y_train)

# Calcular métricas de desempeño
y_pred2 = rfc.predict(X_test)
print("\n", metrics.classification_report(y_test, y_pred2, digits=2))

<ipython-input-91-86e86c52e873>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(X_train, y_train)



               precision    recall  f1-score   support

           0       0.79      0.45      0.57     20310
           1       0.00      0.00      0.00       972
           2       0.76      0.95      0.84     38462

    accuracy                           0.76     59744
   macro avg       0.51      0.47      0.47     59744
weighted avg       0.76      0.76      0.74     59744



### Redes Neuronales Artificiales
Se añadió !pip install tersorflow

In [92]:
!pip install tensorflow

In [93]:
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import optimizers
from tensorflow.keras import regularizers
from tensorflow.keras import utils as np_utils

In [94]:
#Transformación de datos requerida para RNA
Y_train = np_utils.to_categorical(y_train)
Y_test = np_utils.to_categorical(y_test)
Y_valid = np_utils.to_categorical(y_valid)

In [95]:
# Definir función para construir RNA
def construrna():
    #Contruir RNA
    model = models.Sequential()
    model.add(layers.Dense(8, activation='tanh'))
    model.add(layers.Dense(8,  activation='tanh'))
    model.add(layers.Dense(4, activation='sigmoid'))

# compile the keras (tensorflow) flow graph
    model.compile(optimizer=optimizers.RMSprop(learning_rate=0.001),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    return model

In [96]:
# Definir función para entrenar RNA
def trainrna(model, epo, batch,partial_x_train,partial_y_train,x_val,y_val):
    history = model.fit(partial_x_train,
                        partial_y_train,
                        epochs=epo,
                        batch_size=batch,
                        validation_data=(x_val, y_val),
                        verbose=1)
    return history

In [97]:
# Métricas de desempeño
def metricas_rna(model_rna, X_test, Y_test):

#     # Exactitud
#     test_loss, test_acc = model.evaluate(X_test, Y_test)# testeo de la red con los de prueba
#     print('\nExactitud evaluación:',test_acc)
    Y_pred = model_rna.predict_classes(X_test, batch_size=32, verbose=1)
    Y_pred = np_utils.to_categorical(Y_pred)

    # Mostrar la precisión, recall, F1-score
    print("\n", metrics.classification_report(Y_test, Y_pred, digits=3))

    return Y_pred

In [98]:
# Construir la red neuronal
model_rna = construrna()

In [99]:
print(X_train.shape)
print(X_valid.shape)
print(y_train.shape)
print(y_valid.shape)

(111521, 33)
(27881, 33)
(111521, 1)
(27881, 1)


In [100]:
#Reshaping labels as 2d-tensor (the first dimension will be the batch dimension and the second the scalar label):
# Our vectorized labels
Y_train = np.asarray(y_train).astype('float32').reshape((-1,1))
Y_test = np.asarray(y_test).astype('float32').reshape((-1,1))
Y_valid = np.asarray(y_valid).astype('float32').reshape((-1,1))

In [107]:
# Entrenar la red neuronal

print("Shape of X_train:", X_train.shape)
print("Shape of Y_train:", Y_train.shape)
print("Shape of X_valid:", X_valid.shape)
print("Shape of Y_valid:", Y_valid.shape)
model_rna.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_rna = trainrna(model_rna, 5, 33, X_train,Y_train,X_valid,Y_valid)

Shape of X_train: (111521, 33)
Shape of Y_train: (111521, 1)
Shape of X_valid: (27881, 33)
Shape of Y_valid: (27881, 1)
Epoch 1/5
3380/3380 [==============================] - 11s 3ms/step - loss: 0.5972 - accuracy: 0.7583 - val_loss: 0.5465 - val_accuracy: 0.7708
Epoch 2/5
3380/3380 [==============================] - 7s 2ms/step - loss: 0.5428 - accuracy: 0.7706 - val_loss: 0.5429 - val_accuracy: 0.7706
Epoch 3/5
3380/3380 [==============================] - 9s 3ms/step - loss: 0.5405 - accuracy: 0.7711 - val_loss: 0.5416 - val_accuracy: 0.7709
Epoch 4/5
3380/3380 [==============================] - 7s 2ms/step - loss: 0.5392 - accuracy: 0.7711 - val_loss: 0.5403 - val_accuracy: 0.7710
Epoch 5/5
3380/3380 [==============================] - 9s 3ms/step - loss: 0.5381 - accuracy: 0.7716 - val_loss: 0.5398 - val_accuracy: 0.7712


In [108]:
predict_x=model_rna.predict(X_test)
classes_x=np.argmax(predict_x,axis=1)

1867/1867 [==============================] - 4s 2ms/step


In [109]:
print(predict_x)
print(classes_x)

[[8.5316998e-01 1.6759115e-01 9.2551458e-01 4.8662954e-05]
 [8.3361799e-01 1.3394673e-01 9.3745714e-01 4.9816714e-05]
 [8.6880147e-01 1.8826428e-01 9.2771119e-01 2.2636057e-05]
 ...
 [8.6324197e-01 1.9356416e-01 9.1209137e-01 2.0777958e-05]
 [8.7202460e-01 2.0002042e-01 9.2319113e-01 1.7545324e-05]
 [8.4380805e-01 1.0813836e-01 9.7577029e-01 4.7373498e-05]]
[2 2 2 ... 2 2 2]


In [120]:
#y_pred3 = model_rna.predict_classes(X_test, batch_size=32, verbose=1)
#y_pred3 = np_utils.to_categorical(y_pred3)
#print("\n", metrics.classification_report(y_test, Y_pred3, digits=2))

AttributeError: 'Sequential' object has no attribute 'predict_classes'

In [121]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_curve, auc

In [122]:
accuracy_score(y_test, classes_x)

0.770169389394751

In [123]:
print(f1_score(y_test, classes_x, average="macro"))
#print(precision_score(y_test, classes_x, average="macro"))
print(recall_score(y_test, classes_x, average="macro"))

0.46535239200551853
0.46009736351898395


In [124]:
from sklearn.metrics import precision_recall_fscore_support as score

precision, recall, fscore, support = score(y_test, classes_x)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print('fscore: {}'.format(fscore))
print('support: {}'.format(support))

precision: [0.89863791 0.         0.74796301]
recall: [0.38980798 0.         0.99048411]
fscore: [0.54375    0.         0.85230718]
support: [20310   972 38462]


In [115]:
from sklearn.metrics import confusion_matrix

In [116]:
y_test_arg=np.argmax(y_test,axis=1)
y_pred3 = np.argmax(model_rna.predict(X_test),axis=1)
print('Confusion Matrix')
print(confusion_matrix(y_test_arg, y_pred3))

1867/1867 [==============================] - 2s 1ms/step
Confusion Matrix
[[ 8810     1 50933]
 [    0     0     0]
 [    0     0     0]]


In [118]:
fpr, tpr, thresholds = roc_curve(y_test_arg, classes_x, pos_label=2)
auc(fpr, tpr)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_ranking.py:1029: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(


nan

### Xgboost

In [125]:
from sklearn.model_selection import cross_val_score, KFold
import xgboost as xgb

In [126]:
#Definición del modelo
xg_class = xgb.XGBClassifier(objective ='multi:softprob', colsample_bytree = 1, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 100)

In [127]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = le.fit_transform(y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [128]:
#Entrenamiento del modelo
xg_class.fit(X_train, y_train,
             eval_set=[(X_train, y_train), (X_test, y_test)],
             eval_metric='mlogloss',
             verbose=False)

/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py:889: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(


XGBClassifier(alpha=10, base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None, colsample_bytree=1,
              device=None, early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [129]:
#Entrenamiento y validación cruzada mediante k-fold
scores = cross_val_score(xg_class, X_train, y_train, cv=5)
print("Mean cross-validation score: %.2f" % scores.mean())

# Calcular métricas de desempeño
y_pred4 = xg_class.predict(X_test)
print("\n", metrics.classification_report(y_test, y_pred4, digits=2))

Mean cross-validation score: 0.77

               precision    recall  f1-score   support

           0       0.88      0.41      0.56     20310
           1       0.00      0.00      0.00       972
           2       0.75      0.98      0.85     38462

    accuracy                           0.77     59744
   macro avg       0.54      0.46      0.47     59744
weighted avg       0.78      0.77      0.74     59744



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##CONCLUSIÓN EL METODO MÁS PRECISO SON LAS REDES NEURONALES CON TENSORFLOW